services: 
  db:
    image: postgres:13
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tiktok
    ports:
      - "5432:5432"
    networks:
      - tiktok-crawler-network
    restart: 'always'

  # llama:
  #   image: ollama/ollama:latest
  #   volumes:
  #     - .ollama:/root/.ollama
  #     - ./init-ollama.sh:/usr/local/bin/init-ollama.sh
  #   entrypoint: ["/bin/bash", "-c", "/usr/local/bin/init-ollama.sh"]
  #   ports:
  #     - 11434:11434
  #   networks:
  #     - tiktok-crawler-network
  #   restart: 'always'
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]

networks:
    tiktok-crawler-network:
        driver: bridge
 