services: 
  db:
    image: mysql:latest
    volumes:
      -  ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: 'crawler'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'tiktok'
    ports:
      - "3306:3306"
    networks:
      - tiktok-crawler-network
    restart: 'always'

  # llama:
  #   image: ollama/ollama:latest
  #   volumes:
  #     - .ollama:/root/.ollama
  #     - ./init-ollama.sh:/usr/local/bin/init-ollama.sh
  #   entrypoint: ["/bin/bash", "-c", "/usr/local/bin/init-ollama.sh"]
  #   ports:
  #     - 11434:11434
  #   networks:
  #     - tiktok-crawler-network
  #   restart: 'always'
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]

networks:
    tiktok-crawler-network:
        driver: bridge
 